FROM ibmjava:8-jre

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update \
  && apt -y install tzdata \
  && ln -fs /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

ADD mate-api/target/*-SNAPSHOT.jar /applications/mate.jar
ADD mate-simple/target/*-SNAPSHOT.jar /applications/mate-simple.jar

ENTRYPOINT ["/bin/sh","-c","java -jar -Dfile.encoding=UTF-8 /applications/mate.jar --spring.profiles.active=test --server.port=8080"]