FROM openjdk:8-jre

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update \
  && apt -y install tzdata \
  && ln -fs /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

ADD meta-api/target/*-SNAPSHOT.jar /applications/meta.jar
ADD meta-simple/target/*-SNAPSHOT.jar /applications/meta-simple.jar

ENTRYPOINT ["/bin/sh","-c","java -jar -Dfile.encoding=UTF-8 /applications/meta.jar --server.port=8080"]